---
- hosts: localhost
  user: test
  connection: local
  become: false
  gather_facts: no
  vars: 
   user_id:
    - ['123456789012']
    - ['098765432198']
    - ['102938475647'] 
  vars_files:
   - ec2_vars.yml
  tasks:
  - name: launch a temporary instance
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      key_name: "{{ key_name }}"
      image: "{{ image }}"
      group_id: "{{ security_grp }}"
      instance_type: "{{ instance_type }}"
      vpc_subnet_id: "{{ subnet }}"
      wait: yes
      wait_timeout: 500
      exact_count: 1
      count_tag:
        Name: my_ami_builder
      instance_tags:
        Name: my_new_instance
        Type: ami_builder
      assign_public_ip: yes
      user_data: "{{lookup('file', 'user_data.sh')}}"
    register: ami_instance

  - name: Wait for instance to boot by checking ssh port
    wait_for: 
        host: "{{ item.private_ip }}" 
        port: 22 
        delay: 60 
        timeout: 320 
        state: started
    with_items: 
     - "{{ ami_instance.instances }}"
  
  - name: Create AMI
    ec2_ami:
      region: "{{ region }}"
      instance_id: "{{ ami_instance.tagged_instances.0.id }}"
      state: present
      name: my_new_ami
      wait: yes
      launch_permissions:
       user_ids: "{{ user_id }}"
    register: amioutput
    ignore_errors: yes

  - name: Terminate provisioned instance
    ec2:
      region: "{{ region }}"
      instance_ids: "{{ ami_instance.tagged_instances.0.id }}"
      state: 'absent'
